### PR TITLE
Remove floating point string formatting for multiplayer multiplatform compatibility, fixes issue #34 

### LINKED ISSUE #34: Rip out the floating points by the short and curlies
YARM pointed out the possible issue of floating point calculation disparities between platforms, and per <http://www.factorioforums.com/forum/viewtopic.php?p=109051#p109051>, similar happenings have occurred in EvoGUI. Let's see if we can avoid doing much floating point math.

### PR DESCRIPTION
**Pull request by Afforess**
The only sensor using floating points was the evolution factor and pollution around player sensors. Day time, kill count, player locations, and play time all used integers already.

I believe the main problem with floats is that the string.format (which essentially just calls the system library printf or similar) is platform-dependent. This is supported by FFF 108: https://www.factorio.com/blog/post/fff-108 . The gist of the problem, as I understand it, is that the system library may return differing values for Linux, Mac, and Windows. However, there is no differing return values for integers, so doing mathematical trickery to break a floating point number into two integers (the whole number component and fractional decimal component), and printing a floating number as a string made up of two integers should side-step the platform-dependency issues. This fixes #34 [reformatted for auto-close -Narc].

Possibly in the future when Factorio moves to LuaJIT, this will go away (as LuaJIT has it's own platform-independent string formatter), but for now, this code is needed.

### CODE REVIEW

**Comment by narc0tiq** [comment]
I'm not entirely sure FFF 108 is a good reference, in as much as it explicitly refers to `string.format("%g", some_float)` (i.e., the implicit string format used when none is given). Specifying with things like `%0.4f` should still be safe.

That said, I'm going to take this one, if only because you already did the work and it has the potential to help.

File: value_sensors/evolution_factor.lua [hunk 1]
```diff
@@ -4,11 +4,15 @@ local sensor = ValueSensor.new("evolution_factor")
...
+    -- this nonsense is because string.format(%.4f) is not safe in MP across platforms, but integer math is
+    local whole_number = math.floor(percent_evo_factor)
+    local fractional_component = math.floor((percent_evo_factor - whole_number) * 10)
     if self.settings.extra_precision then
-        return {self.format_key, string.format("%0.4f%%", game.evolution_factor * 100)}
+        fractional_component = math.floor((percent_evo_factor - whole_number) * 10000)
     end
 
-    return {self.format_key, string.format("%0.1f%%", game.evolution_factor * 100)}
+    return {self.format_key, string.format("%d.%d%%", whole_number, fractional_component)}
```
Comment (narc0tiq) [inline value_sensors/evolution_factor.lua]: Via <https://forums.factorio.com/viewtopic.php?p=136685#p136685>:

If `percent_evo_factor` is 1.0215 then `fractional_component` is 215 and the `string.format` shows an obviously wrong number.

Fixed in #52.
